# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: :"https://jongdlf27.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
title: Onebell's Dev Blog
description: "A gem-based responsive simple texture styled Jekyll theme."
keywords: 'jekyll,theme,gem-based,blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: github
      url: https://github.com/jongdlf27
home:
  section1: <h1>Onebell's Dev Blog</h1>
  section2: <h2>Welcome to my place:)</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/jongdlf27" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License. 
  footer_content: JongIl's Dev Notes.

disqus:
  shortname: # 
  public_key: # 
google_tag_manager: # 
addthis_public_id: #

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
  intro: /blog/intro/

  